export const queryKeys = {
  me: () => ["me"] as const,
  shops: () => ["shops"] as const,
  items: (
    shopId: string,
    options: { search?: string; categoryId?: string; brandId?: string; page?: number; limit?: number } = {},
  ) => ["items", shopId, options] as const,
  itemsInfinite: (shopId: string, search?: string) => ["items", "infinite", shopId, { search }] as const,
  currentStock: (shopId: string, itemId?: string) => ["current-stock", shopId, { itemId }] as const,
  stockMovements: (shopId: string, itemId?: string, movementType?: string) => ["stock-movements", shopId, { itemId, movementType }] as const,
  sales: (shopId: string) => ["sales", shopId] as const,
  sale: (id: string) => ["sale", id] as const,
  orders: (shopId: string) => ["orders", shopId] as const,
  order: (id: string) => ["order", id] as const,
  customers: (shopId: string) => ["customers", shopId] as const,
  customer: (id: string) => ["customer", id] as const,
  readModels: { bootstrap: (shopId: string) => ["read-models", "bootstrap", shopId] as const },
  payments: (shopId: string, filters?: any) => ["payments", shopId, filters] as const,
  paymentsInfinite: (shopId: string, filters?: any) => ["payments-infinite", shopId, filters] as const,
  currentCashSession: (shopId: string) => ["current-cash-session", shopId] as const,
  cashSessions: (shopId: string) => ["cash-sessions", shopId] as const,
  dailySummary: (shopId: string, date: string) => ["daily-summary", shopId, date] as const,
  dailySummaries: (options: { shopId?: string; dateFrom?: string; dateTo?: string; status?: string }) => ["daily-summaries", options] as const,
  dailySummaryById: (id: string) => ["daily-summary", id] as const,
  notifications: (options: { shopId?: string; unread?: boolean }) => ["notifications", options] as const,
  rateChangeRequests: (options: { shopId?: string; status?: string }) => ["rate-change-requests", options] as const,
  correctionRequests: (options: { shopId?: string; status?: string; entityType?: string }) => ["correction-requests", options] as const,
  auditLogs: (options: { shopId?: string; entityType?: string; action?: string; userId?: string; dateFrom?: string; dateTo?: string }) => ["audit-logs", options] as const,
  cheques: (options: { shopId?: string; status?: string }) => ["cheques", options] as const,
  cheque: (id: string) => ["cheque", id] as const,
  ownerDashboard: (shopId?: string, date?: string) => ["owner-dashboard", { shopId, date }] as const,
  staffTodaySummary: (shopId: string, date?: string, staffId?: string, dateFrom?: string, dateTo?: string) => ["staff-today-summary", shopId, { date, staffId, dateFrom, dateTo }] as const,
  staff: () => ["staff"] as const,
  categories: (shopId: string) => ["categories", shopId] as const,
  attendance: (filters: { shopId?: string; staffId?: string; dateFrom?: string; dateTo?: string }) => ["attendance", filters] as const,
  storageObjects: (shopId: string, filter?: any) => ["storage-objects", shopId, filter] as const,
  storageObjectsInfinite: (shopId: string, filter?: any) => ["storage-objects", "infinite", shopId, filter] as const,
  whatsapp: {
    integration: (shopId: string, integrationId: string) =>
      ["whatsapp", "integration", shopId, integrationId] as const,
    conversations: (
      shopId: string,
      integrationId: string,
      phoneNumberId: string,
      filters: Record<string, unknown> = {},
    ) => ["whatsapp", "conversations", shopId, integrationId, phoneNumberId, filters] as const,
    conversation: (shopId: string, integrationId: string, conversationId: string) =>
      ["whatsapp", "conversation", shopId, integrationId, conversationId] as const,
    messages: (shopId: string, integrationId: string, conversationId: string) =>
      ["whatsapp", "messages", shopId, integrationId, conversationId] as const,
    health: (shopId: string, integrationId: string) =>
      ["whatsapp", "health", shopId, integrationId] as const,
    capability: (shopId: string, integrationId?: string, conversationId?: string) =>
      ["whatsapp", "capability", shopId, integrationId, conversationId] as const,
  },
};
