-- AlterEnum
ALTER TYPE "CustomerLedgerSourceType" ADD VALUE IF NOT EXISTS 'PAYMENT_AMENDMENT';
ALTER TYPE "CustomerLedgerSourceType" ADD VALUE IF NOT EXISTS 'CHEQUE';

-- AlterEnum
ALTER TYPE "CustomerLedgerEntryType" ADD VALUE IF NOT EXISTS 'PAYMENT_VALUE_INCREASE';
ALTER TYPE "CustomerLedgerEntryType" ADD VALUE IF NOT EXISTS 'PAYMENT_VALUE_DECREASE';
ALTER TYPE "CustomerLedgerEntryType" ADD VALUE IF NOT EXISTS 'CHEQUE_BOUNCED';
